title: "My Awesome Book"
author: "Jane Doe"
logo: "images/logo.png"

# Example theme settings
html_theme: "sphinx_book_theme"
html_theme_options:
  repository_url: "https://github.com/username/mynewbook"
  use_repository_button: true

# Misc settings
language: "en"
